name: Run packer validate

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - name: Run tests
      run: |
        cd packer/
        mv variables.json.example variables.json
        pwd
        ls -la 
        packer validate -var-file=variables.json app.json
