name: Run packer validate

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - name: Run tests
      run: |
        mv packer/variables.json.example packer/variables.json
        packer validate -var-file=packer/variables.json packer/app.json
        packer validate -var-file=packer/variables.json packer/db.json
