name: Run terraform validate

on:
  push:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - name: Run terraform validate
      run: |
        terraform -chdir=terraform/stage validate
        terraform -chdir=terraform/prod validate 
